name: Manual Hello World with Variables

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'
      greeting:
        description: 'Greeting message'
        required: false
        default: 'Hello'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world_job:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Print Custom Greeting
      run: echo "${{ github.event.inputs.greeting }}, ${{ github.event.inputs.name }}!"
  get_some_info:
    needs: hello_world_job
    runs-on: self-hosted
    steps:
    - name: Let us dir and pwd
      run: |
        pwd > output.txt
        uname -a >> output.txt
        id >> output.txt
        kubectl version --client ; helm version --short ; docker version --format 'Client: {{.Client.Version}} - Server: {{.Server.Version}}' >> output.txt
    - name: publish artefact
      uses: actions/upload-artifact@v3
      with:
        name: command-output
        path: output.txt
