name: Test pipeline w/ PR creation and push. bonus, calling reusable template

# Controls when the workflow will run

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  name: 'Alex'
  greeting: 'Noroc'
jobs:
  hello_world_job:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Print Custom Greeting
      run: echo "${{ env.greeting }}, ${{ env.name }}!" | tee -a output.txt
  get_some_info:
    needs: hello_world_job
    runs-on: self-hosted
    steps:
    - name: Let us dir and pwd
      run: |
        pwd | tee -a output.txt
        uname -a | tee -a output.txt
        id | tee -a output.txt
    - name: publish artefact
      uses: actions/upload-artifact@v3
      with:
        name: command-output
        path: output.txt
#  here we call a template (aka reusable workflows
  secondary_template_job:
    uses: ./secondary.yaml
    with:
      name: Alex
      greeting: Hello

